server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: user
      password: aws19950630!
  datasource:
    username: ${DATABASE_USERNAME} # 환경변수에 설정함 DATABASE_USERNAME=root;
    password: ${DATABASE_PASSWORD} # 환경변수에 설정함 DATABASE_PASSWORD= *****;
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://project-1.c5mic2ksgw7b.ap-northeast-2.rds.amazonaws.com:3306/innodb?useUnicode=true&characterEncoding=utf8mb4
jpa:
  hibernate:
    ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true

logging:
  level:
    org.hibernate.SQL: ERROR
    org.hibernate.type: ERROR
    org.hibernate.type.descriptor.sql: ERROR
    org.hibernate.stat: ERROR

jwt:
  secret-key-source: ${JWT_SECRET_KEY}  #{JWT_SECRET_KEY} = super-coding ????? ????


#  Server Port ??:
#  server.port:
#    8080: ??????? ?? ??? ??? ??? 8080?? ?????.
#      Spring Security ??:
#      spring.security.user.name:
#        user: ??? ???? ??? ???? ???? "user"?? ??? ??? ?? ???? ?????.
#      spring.security.user.password:
#        1234: ? ???? ??? "1234"? ?????.
#      ?????? ??:
#  spring.datasource.username, spring.datasource.password: ??????? ??? ??? ????? ?? ????? ?????.
#  spring.datasource.driver-class-name: MySQL JDBC ???? ???? ?????.
#  spring.datasource.url: ??????? ??? JDBC URL? ?????.
#  JPA ??:
#  jpa.hibernate.ddl-auto:
#    update: Hibernate?? ??????? ??? ? ?????? ???? ???? ??????? ?????.
#  jpa.hibernate.show-sql:
#    true: ??? SQL ??? ??? ?????.
#  jpa.properties.hibernate.format_sql:
#    true: ???? SQL? ??? ?????.
#  jpa.properties.hibernate.use_sql_comments:
#    true: SQL ??? ??? ???? ??? ?????.
#  jpa.properties.hibernate.generate_statistics:
#    true: Hibernate ??? ????? ?????.
#  ?? ??:
#  SQL ? Hibernate ??? ??? ?? ??? DEBUG? ???? SQL ?? ? Hibernate ??? ??? ?????.
#  JWT ??:
#  jwt.secret-key-source: JWT ??? ?? ?? ?? ???? ?????. ${JWT_SECRET_KEY}? ?? ?? JWT_SECRET_KEY? ?? ?????.

